# NOTE (publication): parameter values in this file are arbitrary plausible stand-ins, not the competition values.
"""D2 quantitative note: probability that a HIDDEN scored case generated by the
a plausible generative process (stand-in parameter magnitudes) falsely trips a gate.
Defensive gate needs a 20-day warm-up at cash 10; test19 needs a 40-day warm-up
at cash 40. We simulate the drift-estimate conditions; the FED0 window is
reported as a separate multiplicative factor (start-rate dependent).
"""
import sys, math, random
sys.path.insert(0, '<WORKDIR>')
from template import (MarketMaker, MarketHistory, MarketParameters, BinaryOption,
                      OptionLeg, Underlying,
                      FED_FUNDS_RATE_UNDERLYING_ID as FID,
                      AJARAI_UNDERLYING_ID as AID,
                      THERIODIC_UNDERLYING_ID as TID)

STANDIN_PARAMS = MarketParameters(
    ajarai_drift=0.0008, ajarai_idio_std_dev=0.012, ajarai_rate_beta=-0.017,
    ajarai_sector_beta=1.0, rate_down_probability=0.21, rate_reversion_strength=0.09,
    rate_up_probability=0.24, sector_std_dev=0.024, theriodic_drift=0.0011,
    theriodic_idio_std_dev=0.015, theriodic_rate_beta=-0.011, theriodic_sector_beta=1.0)

def sim_gate_trip(days, cash, fed0, trials, seed0):
    opt = BinaryOption(legs=(OptionLeg(AID, 1.0),), option_id=1, steps_until_expiry=3, strike=500.0)
    trips_def = trips_t19 = 0
    drift_cond_def = drift_cond_t19 = 0
    for k in range(trials):
        random.seed(seed0 + k)
        vals = {FID: fed0, AID: 800.0, TID: 1100.0}
        rows = [dict(vals)]
        for _ in range(days - 1):
            vals = STANDIN_PARAMS.advance_step(vals)
            rows.append(dict(vals))
        hist = MarketHistory({FID: tuple(r[FID] for r in rows),
                              AID: tuple(r[AID] for r in rows),
                              TID: tuple(r[TID] for r in rows)})
        unds = [Underlying("FED", FID, fed0), Underlying("AJR", AID, rows[-1][AID]),
                Underlying("THR", TID, rows[-1][TID])]
        mm = MarketMaker(unds, [opt], cash)
        mm.warm_up(hist)
        da = mm._estimated_drift_by_id[AID]; dt = mm._estimated_drift_by_id[TID]
        if da < -0.005 and dt > 0.003:
            drift_cond_def += 1
        if da > 0.005 and dt < -0.005:
            drift_cond_t19 += 1
        if mm._is_defensive_environment:
            trips_def += 1
        if mm._is_test_nineteen_environment:
            trips_t19 += 1
    return trips_def, trips_t19, drift_cond_def, drift_cond_t19

N = 1500
# Defensive-shaped hidden case: 20 days, cash 10. FED0=1.5 puts the rate window INSIDE the gate.
td, tt, dcd, dct = sim_gate_trip(20, 10.0, 1.5, N, 42000)
print(f"20d/cash10/FED0=1.5 : defensive trips {td}/{N} = {td/N:.3%} (drift-shape alone {dcd/N:.3%})")
# Same days/cash but FED0=2.0 (outside window): must be 0 regardless of drift shape.
td2, tt2, dcd2, _ = sim_gate_trip(20, 10.0, 2.0, N // 3, 43000)
print(f"20d/cash10/FED0=2.0 : defensive trips {td2}/{N//3} (drift-shape alone {dcd2/(N//3):.3%})")
# Test19-shaped hidden case: 40 days, cash 40, FED0=1.5 inside window.
td3, tt3, _, dct3 = sim_gate_trip(40, 40.0, 1.5, N, 44000)
print(f"40d/cash40/FED0=1.5 : test19 trips {tt3}/{N} = {tt3/N:.3%} (drift-shape alone {dct3/N:.3%})")
# Wrong day-count control: 40 days at cash 10, 20 days at cash 40 -> structurally 0 trips.
a, b, _, _ = sim_gate_trip(40, 10.0, 1.5, N // 3, 45000)
c, d, _, _ = sim_gate_trip(20, 40.0, 1.5, N // 3, 46000)
print(f"controls: 40d/cash10 trips=({a},{b})  20d/cash40 trips=({c},{d})  (expect all 0)")
